// Revised script.js for Michael's Portfolio

const translations = {
  en: {
    pageTitle: "Michael's Portfolio",
    navbarTitle: "Michael Neang",
    heroSubtitle: "Analytics | Insights | Impact",
    aboutDetailTitle: "About Me",
    aboutDetail1: "At 24 years old, I’ve embarked on a dynamic journey as a data analyst—but I’m more than just my job title. My path has been shaped by a strong educational foundation in Information Systems and Operations Management from California State University, Long Beach, along with specialized certifications such as Microsoft’s Power BI Data Analyst (PL‑300) and Tableau’s Certified Data Analyst (TDA‑C01). This blend of formal education and practical expertise has given me a powerful toolkit to help stakeholders uncover hidden stories within their data.",
    aboutDetail2: "Throughout my career, I’ve collaborated with teams in sales operations and supply chain management, refining processes and amplifying performance. Each project has taught me the value of continuous growth and curiosity, fueling my aspiration to evolve into roles such as data engineer or data scientist.",
    carouselCaption1: "My professional headshot",
    carouselCaption2: "Exploring the fusion of digital innovation and art at Tokyo's teamLab Borderless—reflecting my passion for technology and data analytics.",
    carouselCaption3: "Networking internationally with Japan’s Consul-General in LA",
    carouselCaption4: "Embarking on my professional journey at Össur",
    prev: "Previous",
    next: "Next",
    experienceTitle: "Experience",
    exp1Title: "Data Analyst (Sales Operations)",
    exp1Details: "Feb 2023 - Present | Irvine, CA",
    exp2Title: "Global Supply Chain Intern",
    exp2Details: "Jun 2022 - Sep 2022 | Carson, CA",
    exp3Title: "Internal Audit Analyst Intern",
    exp3Details: "Jun 2021 - Aug 2021 | Irvine, CA",
    educationTitle: "Education",
    educationText: "California State University, Long Beach\nBBA in Management Information Systems & Operations Management\nAug 2018 - Dec 2022",
    certificationsTitle: "Certifications",
    cert1Title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    cert2Title: "Microsoft Certified: Azure Data Fundamentals (DP-900)",
    cert3Title: "Microsoft Certified: Azure Fundamentals (AZ-900)",
    cert4Title: "Tableau Certified Data Analyst (TDA-C01)",
    cert5Title: "Alteryx Designer Advanced Certification",
    viewBadge: "View Badge",
    projectsTitle: "Projects",
    proj1Title: "Snapdragon AI: Multilingual Translator",
    proj1Award: "2nd Place out of 27 – Windows on Snapdragon AI Hackathon",
    proj1Text: "An innovative on-device translator for Snapdragon that offers real-time, offline translation between English, Japanese, Korean, and Chinese using optimized AI and Python.",
    proj2Title: "Sakura Guide さくらガイド",
    proj2Text: "A refined travel companion for Japan that blends modern design with real-time guidance to deliver elegant, bilingual travel insights.",
    proj3Title: "Supply Chain Optimization",
    proj3Text: "A focused analysis using Python to uncover inefficiencies in supplier lead times and inventory risk, providing actionable insights for smarter planning.",
    proj4Title: "Retail Superstore Analysis",
    proj4Text: "A thoughtfully designed dashboard built with SQL, Excel, and Tableau that reveals trends in retail performance, empowering strategic decisions.",
    proj5Title: "SmartAInventory",
    proj5Award: "Top 13 out of 83 – Microsoft Fabric and AI Learning Hackathon",
    proj5Text: "A dynamic inventory management system built with Microsoft Fabric, Power BI, and Azure OpenAI that forecasts demand, minimizes risk, and supports agile, insight-led decision-making.",
    skillsTitle: "Key Competencies",
    skillsVisTitle: "Data Visualization & Reporting",
    skillsAnalysisTitle: "Data Analysis & Manipulation",
    skillsDBTitle: "Database & Cloud Technologies",
    skillsExcelTitle: "Excel & Automation",
    skillsGeneralTitle: "General Software",
    contactTitle: "Get in Touch",
    contactNameLabel: "Name:",
    contactEmailLabel: "Email:",
    contactMessageLabel: "Message:",
    sendMessageBtn: "Send Message",
    footerText: "© 2025 Michael Neang. All rights reserved."
  },
  ja: {
    pageTitle: "Michael's Portfolio",
    navbarTitle: "Michael Neang",
    heroSubtitle: "アナリティクス・インサイト・インパクト",
    aboutDetailTitle: "イントロダクション",
    aboutDetail1: "はじめまして。マイキです。24歳でデータアナリストとしてのキャリアをスタートしましたが、肩書きだけでは語れない自分がいます。カリフォルニア州立大学ロングビーチ校での情報システムおよびオペレーション管理の学位に加え、MicrosoftのPower BIデータアナリスト（PL-300）やTableauの認定データアナリスト（TDA‑C01）などの資格を取得し、理論と実践を融合させたスキルセットを身につけました。データの中に隠されたストーリーを発見し、意味のある意思決定へと導くサポートができます。",
    aboutDetail2: "これまでのキャリアでは、営業オペレーションやサプライチェーン部門と密に連携しながら、業務プロセスの改善やパフォーマンスの向上に取り組んできました。プロジェクトを重ねるたびに、分析や戦略だけでなく、学び続ける姿勢と探究心の大切さを実感しています。真のイノベーションは、技術力と創造性が交差する地点から生まれると信じ、将来的にはデータエンジニアやデータサイエンティストとして、より深く組織に貢献していきたいと考えています。",
    carouselCaption1: "私のプロフェッショナルなヘッドショット",
    carouselCaption2: "東京のteamLab Borderlessでテクノロジーとアートの融合を体感",
    carouselCaption3: "ロサンゼルスで日本総領事との出会い",
    carouselCaption4: "Össurでキャリアの第一歩を踏み出す",
    prev: "前へ",
    next: "次へ",
    experienceTitle: "経験",
    exp1Title: "Associate Data Analyst",
    exp1Details: "2023年2月～現在 | Irvine, CA",
    exp2Title: "Global Supply Chain Intern",
    exp2Details: "2022年6月～9月 | Carson, CA",
    exp3Title: "Internal Audit Analyst Intern",
    exp3Details: "2021年6月～8月 | Irvine, CA",
    educationTitle: "学歴",
    educationText: "カリフォルニア州立大学ロングビーチ校\n経営情報システム＆オペレーションマネジメント学士\n2018年8月～2022年12月",
    certificationsTitle: "認定資格",
    cert1Title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    cert2Title: "Microsoft Certified: Azure Data Fundamentals (DP-900)",
    cert3Title: "Microsoft Certified: Azure Fundamentals (AZ-900)",
    cert4Title: "Tableau Certified Data Analyst (TDA-C01)",
    cert5Title: "Alteryx Designer Advanced Certification",
    viewBadge: "認定証を見る",
    projectsTitle: "プロジェクト",
    proj1Title: "Snapdragon AI: 多言語翻訳機",
    proj1Award: "全27チーム中2位 – Windows on Snapdragon AI Hackathon",
    proj1Text: "最先端のAIとPythonを駆使し、英語、日本語、韓国語、中国語間のリアルタイム・オフライン翻訳を実現する多言語オンデバイス翻訳機。効率的で迅速、控えめに力強い。",
    proj2Title: "Sakura Guide さくらガイド",
    proj2Text: "洗練された日本旅行の伴侶。最新のデザインとリアルタイムガイダンスを融合し、優雅なバイリンガルの旅行インサイトを提供します。",
    proj3Title: "Supply Chain Optimization",
    proj3Text: "Pythonを活用し、サプライヤーのリードタイムと在庫リスクの非効率性を明らかにし、具体的で実践的な洞察を提供します。",
    proj4Title: "Retail Superstore Analysis",
    proj4Text: "SQL、Excel、Tableauを駆使して構築された小売パフォーマンスのダッシュボード。傾向とパターンを解析し、戦略的な判断をサポートします。",
    proj5Title: "SmartAInventory",
    proj5Award: "全83チーム中上位13位 – Microsoft Fabric and AI Learning Hackathon",
    proj5Text: "Microsoft Fabric、Power BI、Azure OpenAIを用いたデータ駆動型在庫管理システム。需要予測とリスク低減を実現し、柔軟な意思決定を支援します。",
    skillsTitle: "主要スキル",
    skillsVisTitle: "データ可視化 & レポーティング",
    skillsAnalysisTitle: "データ分析 & 操作",
    skillsDBTitle: "データベース & クラウド技術",
    skillsExcelTitle: "Excel & 自動化",
    skillsGeneralTitle: "一般ソフトウェア",
    contactTitle: "お問い合わせ",
    contactNameLabel: "お名前:",
    contactEmailLabel: "メール:",
    contactMessageLabel: "メッセージ:",
    sendMessageBtn: "送信する",
    footerText: "© 2025 Michael Neang. All rights reserved."
  },
  zh: {
    pageTitle: "Michael's Portfolio",
    navbarTitle: "Michael Neang",
    heroSubtitle: "分析 • 洞察 • 影响",
    aboutDetailTitle: "关于我",
    aboutDetail1: "我今年24岁，踏上了数据分析师的职业旅程。但我并不仅仅是一个头衔。在加州州立大学长滩分校，我打下了信息系统与运营管理的坚实基础，并获得了 Microsoft Power BI（PL‑300）和 Tableau 数据分析师（TDA‑C01）等专业认证。结合理论学习和实践经验，我拥有一套强大的技能工具，能够帮助利益相关者发现数据背后的故事。",
    aboutDetail2: "在职业生涯中，我与销售运营和供应链管理团队紧密合作，不断优化流程并提升绩效。每个项目都让我认识到持续成长与好奇心的重要性，激发了我向数据工程师或数据科学家方向发展的雄心。",
    carouselCaption1: "我的专业头像",
    carouselCaption2: "在东京teamLab Borderless体验科技与艺术的融合",
    carouselCaption3: "在洛杉矶与日本总领事交流",
    carouselCaption4: "在Össur踏出数据分析师的第一步",
    prev: "上一张",
    next: "下一张",
    experienceTitle: "经历",
    exp1Title: "Associate Data Analyst",
    exp1Details: "2023年2月 - 现在 | Irvine, CA",
    exp2Title: "Global Supply Chain Intern",
    exp2Details: "2022年6月 - 9月 | Carson, CA",
    exp3Title: "Internal Audit Analyst Intern",
    exp3Details: "2021年6月 - 8月 | Irvine, CA",
    educationTitle: "教育背景",
    educationText: "加州州立大学长滩分校\n管理信息系统与运营管理学士\n2018年8月 - 2022年12月",
    certificationsTitle: "认证",
    cert1Title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    cert2Title: "Microsoft Certified: Azure Data Fundamentals (DP-900)",
    cert3Title: "Microsoft Certified: Azure Fundamentals (AZ-900)",
    cert4Title: "Tableau Certified Data Analyst (TDA-C01)",
    cert5Title: "Alteryx Designer Advanced Certification",
    viewBadge: "查看认证",
    projectsTitle: "项目",
    proj1Title: "Snapdragon AI: 多语种翻译器",
    proj1Award: "27队中第2名 – Windows on Snapdragon AI Hackathon",
    proj1Text: "专为Snapdragon打造的多语种设备内翻译器，实现英语、日语、韩语及中文之间的实时离线翻译，采用高效AI与Python。轻便、快速且低调强大。",
    proj2Title: "Sakura Guide さくらガイド",
    proj2Text: "为日本之行量身定制的贴心伴侣，融合JavaScript、设计与实时引导，提供优雅且基于位置的双语旅行洞察。",
    proj3Title: "Supply Chain Optimization",
    proj3Text: "利用Python深入分析供应商交货期与库存风险，识别低效环节，并通过清晰的数据洞察支持更优规划。",
    proj4Title: "Retail Superstore Analysis",
    proj4Text: "基于SQL、Excel和Tableau构建的零售绩效仪表板，揭示关键模式与趋势，为智能商业决策提供支持。",
    proj5Title: "SmartAInventory",
    proj5Award: "83队中前13名 – Microsoft Fabric and AI Learning Hackathon",
    proj5Text: "采用Microsoft Fabric、Power BI和Azure OpenAI构建的数据驱动库存系统，实现需求预测、风险降低及敏捷决策。",
    skillsTitle: "核心技能",
    skillsVisTitle: "数据可视化 & 报告",
    skillsAnalysisTitle: "数据分析 & 报告",
    skillsDBTitle: "数据库 & 云技术",
    skillsExcelTitle: "Excel & 自动化",
    skillsGeneralTitle: "常用软件",
    contactTitle: "联系我",
    contactNameLabel: "电子邮件:",
    contactEmailLabel: "电子邮件:",
    contactMessageLabel: "留言:",
    sendMessageBtn: "发送消息",
    footerText: "© 2025 Michael Neang. All rights reserved."
  },
  ko: {
    pageTitle: "Michael's Portfolio",
    navbarTitle: "Michael Neang",
    heroSubtitle: "분석 • 인사이트 • 임팩트",
    aboutDetailTitle: "소개",
    aboutDetail1: "24살의 저는 데이터 분석가로서 활발한 경력을 시작했습니다. 하지만 단순한 직함 이상의 존재입니다. 캘리포니아 주립대학교 롱비치 캠퍼스에서 정보 시스템 및 운영 관리 전공을 통해 이론적 기반을 쌓았고, Microsoft Power BI (PL-300) 및 Tableau 인증 분석가 (TDA-C01) 등의 전문 자격을 통해 실무 능력도 강화했습니다. 이러한 교육과 경험의 조합은 데이터 속 숨겨진 인사이트를 발견하고, 실질적인 의사결정으로 이어지게 하는 능력을 키워주었습니다.",
    aboutDetail2: "지금까지 영업 운영 및 공급망 관리 팀과의 협업을 통해 프로세스를 개선하고 성과를 향상시키는 데 기여해왔습니다. 프로젝트 하나하나가 분석뿐 아니라 지속적인 성장과 호기심의 중요성을 일깨워주었습니다. 진정한 혁신은 기술 역량과 창의성이 만나는 지점에서 탄생한다고 믿으며, 앞으로는 데이터 엔지니어 또는 데이터 사이언티스트로 성장해 조직에 더 깊은 가치를 제공하고자 합니다.",
    carouselCaption1: "내 프로페셔널 헤드샷",
    carouselCaption2: "도쿄 teamLab Borderless에서 첨단 기술의 만남을 체험",
    carouselCaption3: "로스앤젤레스에서 일본 총영사와의 네트워킹",
    carouselCaption4: "Össur에서 데이터 분석가로 첫 발을 내딛는 날",
    prev: "이전",
    next: "다음",
    experienceTitle: "경력",
    exp1Title: "Associate Data Analyst",
    exp1Details: "2023년 2월 - 현재 | Irvine, CA",
    exp2Title: "Global Supply Chain Intern",
    exp2Details: "2022년 6월 - 9월 | Carson, CA",
    exp3Title: "Internal Audit Analyst Intern",
    exp3Details: "2021년 6월 - 8월 | Irvine, CA",
    educationTitle: "학력",
    educationText: "캘리포니아 주립대 롱비치\n경영정보시스템 및 운영관리 학사\n2018년 8월 - 2022년 12월",
    certificationsTitle: "자격증",
    cert1Title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    cert2Title: "Microsoft Certified: Azure Data Fundamentals (DP-900)",
    cert3Title: "Microsoft Certified: Azure Fundamentals (AZ-900)",
    cert4Title: "Tableau Certified Data Analyst (TDA-C01)",
    cert5Title: "Alteryx Designer Advanced Certification",
    viewBadge: "자격증 보기",
    projectsTitle: "프로젝트",
    proj1Title: "Snapdragon AI: 다국어 번역기",
    proj1Award: "27개 팀 중 2위 – Windows on Snapdragon AI Hackathon",
    proj1Text: "Snapdragon용 다국어 온디바이스 번역기로, 영어, 일본어, 한국어, 중국어 간의 실시간 오프라인 번역을 최적화된 AI와 Python으로 구현. 가볍고 빠르며 조용히 강력합니다.",
    proj2Title: "Sakura Guide さくらガ이드",
    proj2Text: "일본 여행의 세련된 동반자 – JavaScript, 디자인, 실시간 가이드를 결합해 양언어 및 위치 기반 여행 인사이트를 우아하게 제공합니다.",
    proj3Title: "Supply Chain Optimization",
    proj3Text: "Python을 활용해 공급업체 리드 타임과 재고 위험을 분석, 비효율성을 식별하고 명확한 데이터 인사이트로 더 나은 계획을 지원합니다.",
    proj4Title: "Retail Superstore Analysis",
    proj4Text: "SQL, Excel, Tableau로 구축된 소매 성과 대시보드로, 패턴과 추세를 파악해 스마트한 비즈니스 결정을 지원합니다.",
    proj5Title: "SmartAInventory",
    proj5Award: "83개 팀 중 상위 13위 – Microsoft Fabric and AI Learning Hackathon",
    proj5Text: "Microsoft Fabric, Power BI, Azure OpenAI를 활용한 데이터 기반 재고 관리 시스템으로, 수요 예측, 위험 감소, 민첩한 의사결정을 지원합니다.",
    skillsTitle: "핵심 역량",
    skillsVisTitle: "데이터 시각화 & 리포팅",
    skillsAnalysisTitle: "데이터 분석 & 조작",
    skillsDBTitle: "데이터베이스 & 클라우드 기술",
    skillsExcelTitle: "Excel & 자동화",
    skillsGeneralTitle: "일반 소프트웨어",
    contactTitle: "문의하기",
    contactNameLabel: "이름:",
    contactEmailLabel: "이메일:",
    contactMessageLabel: "메시지:",
    sendMessageBtn: "메시지 보내기",
    footerText: "© 2025 Michael Neang. All rights reserved."
  }
};

function updateTranslations(lang) {
  const dict = translations[lang];
  for (const key in dict) {
    const elements = document.querySelectorAll(`[data-key="${key}"]`);
    elements.forEach(el => {
      el.textContent = dict[key];
    });
  }
}

document.addEventListener('DOMContentLoaded', () => {
  // Set default language to English
  updateTranslations('en');

  // Handle language switching
  const languageSelect = document.getElementById('languageSelect');
  languageSelect.addEventListener('change', (e) => {
    updateTranslations(e.target.value);
  });
});