// Translation dictionary for culturally-aware, inspiring texts with a cosmopolitan feel
const translations = {
  en: {
    pageTitle: "My Professional Journey",
    navbarTitle: "Hi, I'm Michael",
    heroTitle: "Your Data, My Passion",
    heroSubtitle: "I transform raw numbers into dynamic insights that drive meaningful change.",
    heroButton: "Discover More",
    aboutTitle: "Introduction",
    aboutText: "I am a dedicated data professional who believes in the power of information to spark innovation and drive progress. With a robust background in Information Systems and Operations Management, I approach every challenge with creativity and commitment. Data isn’t just numbers—it’s the catalyst for growth and innovation. Join me on this journey as I harness data to unlock potential and shape the future.",
    galleryTitle: "Gallery",
    carousel1: "Capturing the vibrant energy of Tokyo’s teamLab Borderless",
    carousel2: "Sharing a memorable moment with Japan’s Consul-General in LA",
    carousel3: "Embarking on my data journey at Össur",
    prev: "Previous",
    next: "Next",
    experienceTitle: "Experience",
    exp1Title: "Associate Data Analyst",
    exp1Details: "Feb 2023 - Present | Irvine, CA",
    exp2Title: "Global Supply Chain Intern",
    exp2Details: "Jun 2022 - Sep 2022 | Carson, CA",
    exp3Title: "Internal Audit Analyst Intern",
    exp3Details: "Jun 2021 - Aug 2021 | Irvine, CA",
    educationTitle: "Education",
    educationText: "California State University, Long Beach\nBBA in Management Information Systems & Operations Management\nAug 2018 - Dec 2022",
    certificationsTitle: "Certifications",
    cert1Title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    cert2Title: "Microsoft Certified: Azure Data Fundamentals (DP-900)",
    cert3Title: "Microsoft Certified: Azure Fundamentals (AZ-900)",
    cert4Title: "Tableau Certified Data Analyst (TDA-C01)",
    cert5Title: "Alteryx Designer Advanced Certification",
    viewBadge: "View Badge",
    projectsTitle: "Projects",
    proj1Title: "Snapdragon AI: Multilingual Translator",
    proj1Award: "2nd Place out of 27 – Windows on Snapdragon AI Hackathon",
    proj1Text: "An innovative on-device translator for Snapdragon that offers real-time, offline translation between English, Japanese, Korean, and Chinese using optimized AI and Python.",
    proj2Title: "Sakura Guide さくらガイド",
    proj2Text: "A refined travel companion for Japan that blends modern design with real-time guidance to deliver elegant, bilingual travel insights.",
    proj3Title: "Supply Chain Optimization",
    proj3Text: "A focused analysis using Python to uncover inefficiencies in supplier lead times and inventory risk, providing actionable insights for smarter planning.",
    proj4Title: "Retail Superstore Analysis",
    proj4Text: "A thoughtfully designed dashboard built with SQL, Excel, and Tableau that reveals trends in retail performance, empowering strategic decisions.",
    proj5Title: "SmartAInventory",
    proj5Award: "Top 13 out of 83 – Microsoft Fabric and AI Learning Hackathon",
    proj5Text: "A dynamic inventory management system built with Microsoft Fabric, Power BI, and Azure OpenAI that forecasts demand, minimizes risk, and supports agile, insight-led decision-making.",
    skillsTitle: "Key Competencies",
    skillsVisTitle: "Data Visualization & Reporting",
    skillsAnalysisTitle: "Data Analysis & Manipulation",
    skillsDBTitle: "Database & Cloud Technologies",
    skillsExcelTitle: "Excel & Automation",
    skillsGeneralTitle: "General Software",
    contactTitle: "Get in Touch",
    contactNameLabel: "Name:",
    contactEmailLabel: "Email:",
    contactMessageLabel: "Message:",
    sendMessageBtn: "Send Message",
    footerText: "© 2025 Michael Neang. All rights reserved."
  },
  ja: {
    pageTitle: "私のプロフェッショナル・ジャーニー",
    navbarTitle: "こんにちは、マイケルです",
    heroTitle: "データに情熱を、未来に挑む",
    heroSubtitle: "情報を力に変え、イノベーションと成長を生み出す。",
    heroButton: "もっと知る",
    aboutTitle: "イントロダクション",
    aboutText: "私は、データを通して革新を促し、進歩を実現する情熱を持つプロフェッショナルです。情報システムとオペレーションマネジメントの確固たる基盤を活かし、創造性と献身をもってあらゆる挑戦に取り組んでいます。データは単なる数字ではなく、未来を切り拓く原動力です。共に可能性を広げ、変革を起こしましょう。",
    galleryTitle: "ギャラリー",
    carousel1: "東京のteamLab Borderlessの輝きを体感",
    carousel2: "ロサンゼルスで総領事との心温まるひととき",
    carousel3: "Össurで初めてのデータ分析の日",
    prev: "前へ",
    next: "次へ",
    experienceTitle: "経験",
    exp1Title: "Associate Data Analyst",
    exp1Details: "2023年2月～現在 | Irvine, CA",
    exp2Title: "Global Supply Chain Intern",
    exp2Details: "2022年6月～9月 | Carson, CA",
    exp3Title: "Internal Audit Analyst Intern",
    exp3Details: "2021年6月～8月 | Irvine, CA",
    educationTitle: "学歴",
    educationText: "カリフォルニア州立大学ロングビーチ校\n経営情報システム＆オペレーションマネジメント学士\n2018年8月～2022年12月",
    certificationsTitle: "認定資格",
    cert1Title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    cert2Title: "Microsoft Certified: Azure Data Fundamentals (DP-900)",
    cert3Title: "Microsoft Certified: Azure Fundamentals (AZ-900)",
    cert4Title: "Tableau Certified Data Analyst (TDA-C01)",
    cert5Title: "Alteryx Designer Advanced Certification",
    viewBadge: "認定証を見る",
    projectsTitle: "プロジェクト",
    proj1Title: "Snapdragon AI: 多言語翻訳機",
    proj1Award: "全27チーム中2位 – Windows on Snapdragon AI Hackathon",
    proj1Text: "最先端のAIとPythonを駆使し、英語、日本語、韓国語、中国語間のリアルタイム・オフライン翻訳を実現する多言語オンデバイス翻訳機。効率的で迅速、控えめに力強い。",
    proj2Title: "Sakura Guide さくらガイド",
    proj2Text: "洗練された日本旅行の伴侶。最新のデザインとリアルタイムガイダンスを融合し、優雅なバイリンガルの旅行インサイトを提供します。",
    proj3Title: "Supply Chain Optimization",
    proj3Text: "Pythonを活用し、サプライヤーのリードタイムと在庫リスクの非効率性を明らかにし、具体的で実践的な洞察を提供します。",
    proj4Title: "Retail Superstore Analysis",
    proj4Text: "SQL、Excel、Tableauを駆使して構築された小売パフォーマンスのダッシュボード。傾向とパターンを解析し、戦略的な判断をサポートします。",
    proj5Title: "SmartAInventory",
    proj5Award: "全83チーム中上位13位 – Microsoft Fabric and AI Learning Hackathon",
    proj5Text: "Microsoft Fabric、Power BI、Azure OpenAIを用いたデータ駆動型在庫管理システム。需要予測とリスク低減を実現し、柔軟な意思決定を支援します。",
    skillsTitle: "主要スキル",
    skillsVisTitle: "データ可視化 & レポーティング",
    skillsAnalysisTitle: "データ分析 & 操作",
    skillsDBTitle: "データベース & クラウド技術",
    skillsExcelTitle: "Excel & 自動化",
    skillsGeneralTitle: "一般ソフトウェア",
    contactTitle: "お問い合わせ",
    contactNameLabel: "お名前:",
    contactEmailLabel: "メール:",
    contactMessageLabel: "メッセージ:",
    sendMessageBtn: "送信する",
    footerText: "© 2025 Michael Neang. All rights reserved."
  },
  zh: {
    pageTitle: "我的职业旅程",
    navbarTitle: "嗨，我是Michael",
    heroTitle: "用数据点亮未来",
    heroSubtitle: "我将原始数据转化为驱动深远变革的智慧洞察。",
    heroButton: "了解更多",
    aboutTitle: "简介",
    aboutText: "我是一位专注于数据的专业人士，相信信息的力量能够启迪创新和推动进步。凭借扎实的信息系统和运营管理背景，我以创造性和决心迎接每一个挑战。数据不仅仅是数字，它是激发成长与革新的源泉。让我们一起探索未来的无限可能。",
    galleryTitle: "画廊",
    carousel1: "感受东京teamLab Borderless的璀璨光芒",
    carousel2: "与日本总领事在洛杉矶共享温馨时刻",
    carousel3: "作为Össur数据分析师的第一天",
    prev: "上一张",
    next: "下一张",
    experienceTitle: "经历",
    exp1Title: "Associate Data Analyst",
    exp1Details: "2023年2月 - 现在 | Irvine, CA",
    exp2Title: "Global Supply Chain Intern",
    exp2Details: "2022年6月 - 9月 | Carson, CA",
    exp3Title: "Internal Audit Analyst Intern",
    exp3Details: "2021年6月 - 8月 | Irvine, CA",
    educationTitle: "教育背景",
    educationText: "加州州立大学长滩分校\n管理信息系统与运营管理学士\n2018年8月 - 2022年12月",
    certificationsTitle: "认证",
    cert1Title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    cert2Title: "Microsoft Certified: Azure Data Fundamentals (DP-900)",
    cert3Title: "Microsoft Certified: Azure Fundamentals (AZ-900)",
    cert4Title: "Tableau Certified Data Analyst (TDA-C01)",
    cert5Title: "Alteryx Designer Advanced Certification",
    viewBadge: "查看认证",
    projectsTitle: "项目",
    proj1Title: "Snapdragon AI: 多语种翻译器",
    proj1Award: "27队中第2名 – Windows on Snapdragon AI Hackathon",
    proj1Text: "专为Snapdragon打造的多语种设备内翻译器，实现英语、日语、韩语及中文之间的实时离线翻译，采用高效AI与Python。轻便、快速且低调强大。",
    proj2Title: "Sakura Guide さくらガイド",
    proj2Text: "为日本之行量身定制的贴心伴侣，融合JavaScript、设计与实时引导，提供优雅且基于位置的双语旅行洞察。",
    proj3Title: "Supply Chain Optimization",
    proj3Text: "利用Python深入分析供应商交货期与库存风险，识别低效环节，并通过清晰的数据洞察支持更优规划。",
    proj4Title: "Retail Superstore Analysis",
    proj4Text: "基于SQL、Excel和Tableau构建的零售绩效仪表板，揭示关键模式与趋势，为智能商业决策提供支持。",
    proj5Title: "SmartAInventory",
    proj5Award: "83队中前13名 – Microsoft Fabric and AI Learning Hackathon",
    proj5Text: "采用Microsoft Fabric、Power BI和Azure OpenAI构建的数据驱动库存系统，实现需求预测、风险降低及敏捷决策。",
    skillsTitle: "核心技能",
    skillsVisTitle: "数据可视化 & 报告",
    skillsAnalysisTitle: "数据分析 & 操作",
    skillsDBTitle: "数据库 & 云技术",
    skillsExcelTitle: "Excel & 自动化",
    skillsGeneralTitle: "常用软件",
    contactTitle: "联系我",
    contactNameLabel: "姓名:",
    contactEmailLabel: "电子邮件:",
    contactMessageLabel: "留言:",
    sendMessageBtn: "发送消息",
    footerText: "© 2025 Michael Neang. All rights reserved."
  },
  ko: {
    pageTitle: "내 프로페셔널 여정",
    navbarTitle: "안녕하세요, 저는 Michael입니다",
    heroTitle: "데이터로 미래를 밝히다",
    heroSubtitle: "데이터의 힘으로 혁신을 이끌며 새로운 변화를 만들어갑니다.",
    heroButton: "더 알아보기",
    aboutTitle: "소개",
    aboutText: "저는 데이터의 가치를 믿는 전문가로서, 정보시스템 및 운영관리 분야에서 쌓은 탄탄한 경험을 바탕으로 창의적이고 혁신적인 솔루션을 제공합니다. 데이터는 단순한 숫자가 아니라, 미래를 개척하는 열쇠입니다. 저와 함께 그 가능성을 실현해보세요.",
    galleryTitle: "갤러리",
    carousel1: "도쿄 teamLab Borderless의 찬란한 빛을 체험",
    carousel2: "로스앤젤레스에서 일본 총영사와 소중한 순간을 나누다",
    carousel3: "Össur에서 데이터 분석가로 첫 발을 내딛은 날",
    prev: "이전",
    next: "다음",
    experienceTitle: "경력",
    exp1Title: "Associate Data Analyst",
    exp1Details: "2023년 2월 - 현재 | Irvine, CA",
    exp2Title: "Global Supply Chain Intern",
    exp2Details: "2022년 6월 - 9월 | Carson, CA",
    exp3Title: "Internal Audit Analyst Intern",
    exp3Details: "2021년 6월 - 8월 | Irvine, CA",
    educationTitle: "학력",
    educationText: "캘리포니아 주립대 롱비치\n경영정보시스템 및 운영관리 학사\n2018년 8월 - 2022년 12월",
    certificationsTitle: "자격증",
    cert1Title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    cert2Title: "Microsoft Certified: Azure Data Fundamentals (DP-900)",
    cert3Title: "Microsoft Certified: Azure Fundamentals (AZ-900)",
    cert4Title: "Tableau Certified Data Analyst (TDA-C01)",
    cert5Title: "Alteryx Designer Advanced Certification",
    viewBadge: "자격증 보기",
    projectsTitle: "프로젝트",
    proj1Title: "Snapdragon AI: 다국어 번역기",
    proj1Award: "27개 팀 중 2위 – Windows on Snapdragon AI Hackathon",
    proj1Text: "Snapdragon용 다국어 온디바이스 번역기로, 영어, 일본어, 한국어, 중국어 간의 실시간 오프라인 번역을 최적화된 AI와 Python으로 구현. 가볍고 빠르며 조용히 강력합니다.",
    proj2Title: "Sakura Guide さくらガ이드",
    proj2Text: "일본 여행의 세련된 동반자 – JavaScript, 디자인, 실시간 가이드를 결합해 양언어 및 위치 기반 여행 인사이트를 우아하게 제공합니다.",
    proj3Title: "Supply Chain Optimization",
    proj3Text: "Python을 활용해 공급업체 리드 타임과 재고 위험을 분석, 비효율성을 식별하고 명확한 데이터 인사이트로 더 나은 계획을 지원합니다.",
    proj4Title: "Retail Superstore Analysis",
    proj4Text: "SQL, Excel, Tableau로 구축된 소매 성과 대시보드로, 패턴과 추세를 파악해 스마트한 비즈니스 결정을 지원합니다.",
    proj5Title: "SmartAInventory",
    proj5Award: "83개 팀 중 상위 13위 – Microsoft Fabric and AI Learning Hackathon",
    proj5Text: "Microsoft Fabric, Power BI, Azure OpenAI를 활용한 데이터 기반 재고 관리 시스템으로, 수요 예측, 위험 감소, 민첩한 의사결정을 지원합니다.",
    skillsTitle: "핵심 역량",
    skillsVisTitle: "데이터 시각화 & 리포팅",
    skillsAnalysisTitle: "데이터 분석 & 조작",
    skillsDBTitle: "데이터베이스 & 클라우드 기술",
    skillsExcelTitle: "Excel & 자동화",
    skillsGeneralTitle: "일반 소프트웨어",
    contactTitle: "문의하기",
    contactNameLabel: "이름:",
    contactEmailLabel: "이메일:",
    contactMessageLabel: "메시지:",
    sendMessageBtn: "메시지 보내기",
    footerText: "© 2025 Michael Neang. All rights reserved."
  }
};

function updateTranslations(lang) {
  const dict = translations[lang];
  for (const key in dict) {
    const elements = document.querySelectorAll(`[data-key="${key}"]`);
    elements.forEach(el => {
      el.textContent = dict[key];
    });
  }
}

document.addEventListener('DOMContentLoaded', () => {
  // Set default language to English
  updateTranslations('en');

  // Handle language switching
  const languageSelect = document.getElementById('languageSelect');
  languageSelect.addEventListener('change', (e) => {
    updateTranslations(e.target.value);
  });

  // No special JS needed for the vertical carousel aside from the default 
  // Bootstrap behavior. If you'd like to place controls top/bottom, you can
  // do so with additional custom CSS or by re-positioning the .carousel-control elements.
});